### ISSUE TITLE
LogBlock possibly causing high amounts of lag with 1.6.0?

### ISSUE THREAD

**Issue by clucky** [LogBlock/LogBlock#274]
My server has been experiencing high amounts of lag recently. According to NoLagg, this is either due to LogBlock or #Chunk Provider (whatever this is). Here is the NoLagg examination: ![NoLagg Examine](http://worldofclucky.net/errors/LogBlock/exam.png)

Here is my config:

```
tools:
  tool:
    defaultEnabled: true
    mode: LOOKUP
    aliases:
    - t
    params: area 0 all sum none limit 15 desc silent
    leftClickBehavior: none
    item: 120
    rightClickBehavior: none
    permissionDefault: OP
    canDrop: true
  toolblock:
    params: area 0 all sum none limit 15 desc silent
    permissionDefault: OP
    rightClickBehavior: BLOCK
    item: 120
    mode: LOOKUP
    canDrop: false
    defaultEnabled: true
    aliases:
    - tb
    leftClickBehavior: TOOL
mysql:
  user: clucky
  port: 3306
  password: 6783122131125678876
  host: localhost
  database: frisnuk_logblock
logging:
  hiddenBlocks:
  - 0
  logCreeperExplosionsAsPlayerWhoTriggeredThese: true
  logPlayerInfo: true
  ignoredChat: []
  hiddenPlayers: []
  logKillsLevel: ANIMALS
consumer:
  timePerRun: 200
  useBukkitScheduler: true
  forceToProcessAtLeast: 20
  delayBetweenRuns: 6
lookup:
  dateFormat: MM-dd HH:mm:ss
  linesLimit: 1500
  defaultTime: 30 minutes
  defaultDist: 20
  linesPerPage: 15
questioner:
  askClearLogs: true
  banPermission: mcbans.ban.local
  askRollbacks: true
  askRedos: true
  askClearLogAfterRollback: true
  askRollbackAfterBan: false
loggedWorlds:
- Frisnuk
- Frisnuk_nether
- Frisnuk_the_end
clearlog:
  enableAutoClearLog: false
  auto:
  - world "world" before 365 days all
  - world "world" player lavaflow waterflow leavesdecay before 7 days all
  - world world_nether before 365 days all
  - world world_nether player lavaflow before 7 days all
  autoClearLogDelay: 6h
  dumpDeletedLog: false
rollback:
  replaceAnyway:
  - 8
  - 9
  - 10
  - 11
  - 51
  maxArea: 50
  dontRollback: []
  maxTime: 2 days
version: '1.60'
```

Any thoughts? Here is my plugin list:

> [INFO] Plugins (55): PlugMan, Vault, Multiverse-Core, ConsoleFilter, dynmap, DynamicEffectWhitelist, BanManager, PopulationDensity, ProtocolLib, CleanroomGenerator, PwnFilter, WorldEdit, NoCheatPlus, GiveAll, Multiverse-Inventories, AutoShutdown, DeathControl, PermissionsEx, LogBlock, WorldGuard, WitherManagement, boosCooldowns, SimpleCalc, MessageChangerLite, SignEdit, iConomy, PluginList, pvparena, MobSpawnControl, BKCommonLib, GetPerms, Modifyworld, Essentials, ShowCaseStandalone, Orebfuscator, WorldBorder, CreeperHeal, Multiverse-Portals, RecipeManager, rTriggers, Reporter, NoLagg, Residence, ChatManager, EssentialsSpawn, OtherDrops, EssentialsGeoIP, VanishNoPacket, LWC, ResidenceSigns, DeathTpPlus, dynmap-residence, SimpleClans, SimpleClansResidence, PreciousStones
