### ISSUE TITLE
LogBlock @ 25+ players

### ISSUE THREAD

**Issue by LefsFlare** [LogBlock/LogBlock#580]
Hello, I wouldn't open a ticket for nothing but I've really been left at wits end.

This is my current situation, I'm a developer attached to one of a server that has been growing lately and I've been fighting queue overloads here and there but I realized that once player count increases beyond 20-25, the queue increases drastically.

This is my config
```
consumer:
  timePerRun: 3600
  useBukkitScheduler: false
  forceToProcessAtLeast: 10
  queueWarningSize: 10000
  fireCustomEvents: true
  delayBetweenRuns: 1
```
Is my configuration wrong?

I am currently attaching LogBlock to a remote SQL server that I've custom configured on my part so the SQL server part isn't lagging. Here's my question though, in every INSERT SQL command, there's a way to specify multiple values into one query, which could virtually compress all the queries down for even FASTER saving to SQL databases. I feel that this could be the most urgent ticket that should be worked on immediately as if multiple INSERT queries are compressed into a few, that would virtually solve my problem and increase performance at the same time.

However, if that's not possible, can we at least have multiple consumer threads?
