### ISSUE TITLE
REF unable to clear table entries #593 #594

### ISSUE THREAD

**Issue by frizzbee30** [LogBlock/LogBlock#603]
Hi, this still appears to be an issue sadly, just updated to #249 and it is still unable to recognise the Survival Map entry? Do I just need to change th eworld name format after the update to suit the parser fix? Thanks

error

http://pastebin.com/2xu8AYNW

config

http://pastebin.com/3p49KhEi

**Comment by frymaster** [comment]
can you paste the output of the command ``/version logblock`` please?

**Comment by frizzbee30** [comment]
hi, as below

20.03 13:22:00 [Server] INFO Authors: DiddiZ, md_5, ammar2 and frymaster
 
20.03 13:22:00 [Server] INFO Website: http://dev.bukkit.org/server-mods/logblock/
 
20.03 13:22:00 [Server] INFO Logs blocks.
 
20.03 13:22:00 [Server] INFO LogBlock version 1.94-dev-SNAPSHOT (build #249)

**Comment by ammaraskar** [comment]
That's odd, I put this in my config
```yaml
clearlog:
  enableAutoClearLog: true
  auto:
  - world "Survival Map" before 14 days all
  - world "world" before 3 days all
```

and it gave me this ``There is no world called 'Survival Map'``
but for you it gives ``There is no world called 'Survival'``
