### ISSUE TITLE
idea] Toggleable defaults from LB config

### ISSUE THREAD

**Issue by rautamiekka** [LogBlock/LogBlock#639]
It'd be better if LB's config had a way to define the defaults you want to use, not the ones LB has, for new worlds.

Example additions to the config:
```yaml
#Toggle between using LB's defaults and your defaults for new worlds:
enable_custom_defaults: false
#List of options:
custom_defaults:
    FIRE: false
    BONEMEALSTRUCTUREGROW: false
    DOORINTERACT: false
    BLOCKBREAK: false
    DIODEINTERACT: false
    SIGNTEXT: false
    WATERFLOW: false
    CAKEEAT: false
    MYCELIUMSPREAD: false
    NOTEBLOCKINTERACT: false
    VINEGROWTH: false
    ENDERDRAGON: false
    BLOCKPLACE: false
    SNOWFORM: false
    COMPARATORINTERACT: false
    SWITCHINTERACT: false
    ENDERMEN: false
    GHASTFIREBALLEXPLOSION: false
    SNOWFADE: false
    TRIPWIREINTERACT: false
    TNTMINECARTEXPLOSION: false
    WITHER: false
    CREEPEREXPLOSION: false
    MISCEXPLOSION: false
    LAVAFLOW: false
    CHESTACCESS: false
    CHAT: false
    WITHER_SKULL: false
    CROPTRAMPLE: false
    TNTEXPLOSION: false
    KILL: false
    GRASSGROWTH: false
    PRESUREPLATEINTERACT: false
    WORLDEDIT: false
    LEAVESDECAY: false
    MUSHROOMSPREAD: false
    CREATURECROPTRAMPLE: false
    LOCKEDCHESTDECAY: false
    NATURALSTRUCTUREGROW: false
```
