### ISSUE TITLE
If §kills§ param is in the config in one of the tools' params, that tool becomes unknown command

### ISSUE THREAD

**Issue by rautamiekka** [LogBlock/LogBlock#642]
LB 1.81 and 1.10-snapshot-263 tested, you can create synthetic unknown commands by adding the `kills` param to any of the tools' params in the main config, like this:

``` yml
tools:
  toolblock:
    item: 7
    canDrop: false
    leftClickBehavior: TOOL
    mode: LOOKUP
    aliases:
    - tb
    rightClickBehavior: BLOCK
    defaultEnabled: true
    permissionDefault: OP
    params: area 0 all sum none limit 15 desc silent kills
```

Likewise, the tool doesn't work by doing that, becoming a regular item.
