### ISSUE TITLE
Problems with /lb tool 

### ISSUE THREAD

**Issue by DeVoX1** [LogBlock/LogBlock#776]
Hi,
I have a problem with logblock when I type the command / lb tool displays a message unknown command "tool"

**Comment by Brokkonaut** [comment]
Looks like you deleted/broke the tools section in the config.yml

It should be something like this (every available tool has its own subsection, the name of the tool is the name of the subsection):

```yaml
tools:
  tool:
    defaultEnabled: true
    mode: LOOKUP
    aliases:
    - t
    params: area 0 all sum none limit 50 desc silent nocache
    leftClickBehavior: NONE
    item: WOODEN_PICKAXE
    rightClickBehavior: TOOL
    permissionDefault: OP
    canDrop: true
    dropToDisable: true
    removeOnDisable: false
  toolblock:
    params: area 0 all sum none limit 50 desc silent nocache
    permissionDefault: OP
    rightClickBehavior: BLOCK
    item: OAK_LOG
    mode: LOOKUP
    defaultEnabled: true
    aliases:
    - tb
    leftClickBehavior: TOOL
    canDrop: true
    removeOnDisable: false
    dropToDisable: true
```
