### ISSUE TITLE
MySQL hangs when LogBlock tries to clearlog

### ISSUE THREAD

**Issue by Gerolfing** [LogBlock/LogBlock#789]
When LogBlock tries to make autoclear log MySQL starts to load 1 thread to 100% endlessly (until restart of MySQL servive), and LogBLock looses connection to it and can't reconnect. Is there anything I can do to fix this? I think it's because main database has weight 8.8 Gb. Is there any way to reduce it softly, without hanging the whole thing?

**Comment by Brokkonaut** [comment]
What are your clearlog parameters? Keeping the query simpler might reduce the time needed.

Generally clearlog can take some time but as it works in the background it should not cause any problems. Maybe you should increase the timeout settings for the mysql server: https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout or https://support.rackspace.com/how-to/how-to-change-the-mysql-timeout-on-a-server/

**Comment by Gerolfing** [comment]
> What are your clearlog parameters? Keeping the query simpler might reduce the time needed.

Clearlog parameters:
```
clearlog:
  auto:
  - world "2015" before 110 days all
  - world "2015" player lavaflow waterflow leavesdecay before 17 days all
  - world "2015" entities before 110 days
  - world "2015_nether" before 100 days all
  - world "2015_nether" player lavaflow waterflow leavesdecay before 17 days all
  - world "2015_nether" entities before 100 days
  - world "2015_the_end" before 100 days all
  - world "2015_the_end" player lavaflow waterflow leavesdecay before 17 days all
  - world "2015_the_end" entities before 100 days
  dumpDeletedLog: false
  autoClearLogDelay: 6h
  enableAutoClearLog: true
```
It don't work in background, because while mysql process heavily loads CPU it don't use storage I/O, meaning it don't erase anything and database size is not shrinking. And what's worse during this "hangup" Log block looses connection to database (other plugins with mysql databases continue to work fine) and only after server and mysql restart log block uploads dumps to database, but players report missing logs for their actions, so it's bad. I think direct mysql terminal command that will delete all logs before  sertain date is resolution of my problem
