### ISSUE TITLE
Question: how to clean everything for past 30 days.

### ISSUE THREAD

**Issue by andrewkm** [LogBlock/LogBlock#790]
I'm having a bit of trouble figuring how to get clearlog to do exactly what I want.
My question is simple, how do I set clearing for basically everything older than 30 days every 6 hours.

Would the following be correct:
```
clearlog:
  auto:
  - world "lobby" before 30 days all
  - world "lobby" player lavaflow waterflow leavesdecay before 30 days all
  - world "lobby" entities before 30 days
  dumpDeletedLog: false
  autoClearLogDelay: 6h
  enableAutoClearLog: true
```

Or is that too much, do I only need **world "lobby" before 30 days all**?
PS: What does the "all" do at the end of those lines?

**Comment by Brokkonaut** [comment]
Those clearlog parameters are the same as query parameters, they are documented here: https://github.com/LogBlock/LogBlock/wiki/Params So "all" is all block modifications including chest access, but not entity modifications or chat logs.

Because of this you do not need the second line that will only remove logs for the "actors" lavaflow waterflow and leavesdecay (some servers use that to remove logs created by those actors earlier).

So what I would recommend is something like:
```
  auto:
  - world "lobby" all before 30 days
  - world "lobby" entities before 30 days
```
If you use the command/chat logging feature you could also add clearlog for the chat:
```
  - chat before 30 days
```

**Comment by andrewkm** [comment]
Thank you.
Yes we use every single possible logging feature selected to true. And the goal is to clear basically everything that's older than 30 days at a 6 hour interval :)

**Comment by andrewkm** [comment]
Alright got this going, assuming it's good :)

```
clearlog:
  auto:
  - world "lobby" before 30 days
  - world "lobby" entities before 30 days
  - world "lobby" chat before 30 days
```

Thanks! <3

**Comment by andrewkm** [comment]
Question regarding our 1.12.2 servers.
We are running the following settings:

```
clearlog:
  enableAutoClearLog: true
  auto:
  - world "rising" all before 30 days
  - world "rising" entities before 30 days
  - world "rising" chat before 30 days
  - world "legacy" all before 30 days
  - world "legacy" entities before 30 days
  - world "legacy" chat before 30 days
  autoClearLogDelay: 6h
  dumpDeletedLog: false
```

However it seems there's an issue as I get the following in console twice (perhaps two are incorrect):
https://pastebin.com/raw/3WXY72rv

Any ideas what the commands would be on LogBlock build 282
(https://ci.md-5.net/job/LogBlock/282/)
The last one prior to 1.13 update.
