### ISSUE TITLE
[Feature request] Automatically log new world?

### ISSUE THREAD

**Issue by bobhenl** [LogBlock/LogBlock#801]
Hi, could you add option to automatically log new worlds? I have build server and there are every builds in new world, so I need to log new worlds there. Automatically, if it's possible

**Comment by CDWimmer** [comment]
Even a simple command to register a new world as being logged would be great.

**Comment by KleinCrafter** [comment]
I think, I can add it with #744 (layered world configuration)
`config.yml` would extended like this
```yaml
autoLog:
  # If enabled, loggedWorlds will be ignored
  OVERWORLD: false
  NETHER: false
  THE_END: false
```
The `world-default.yml` would extended like this
```yaml
# if autoLog.enable is false log will be ignored
log: true
table: default
```

table name `default` would be replaced by the logblock notation `lb-` followed by the world name.
If autoLog is enabled, single worlds can be ignored by the world specific configuration.

If a world dimension not in autoLog enabled and not listed in loggedWorlds, the world will not be loggt.
If a world in one of the both, the world specific configuration (layer) will be used.
